# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose


# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: nina
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#        - USER_NAME=nwachter
#          # The Zohomail ids
#        - MAIL_RECIPIENT=trashkan18@gmail.com
 #       - MAIL_SENDER=ninjaevents@zohomail.eu
#        - MAIL_APP_PASSWORD=x
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt


#services:
#  server:
 #   build:
#      context: .
 #   ports:
#      - 9000:80

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    #image: php:8.2-apache 
    container_name: php-app
    ports: 
      - 8080:80
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - web-code:/var/www/html/ProjetEvenements # Mount PHP code
      - ./logs:/var/log/apache2  # Optional: Apache logs


  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: mysql:8.0
    restart: always
    user: "1000:1000"  #

    secrets:
      - db-password
      - db-root-password
    volumes:
      - ./db/db-data:/var/lib/mysql:Z # MySQL stores data here, testerror : add :Z to fix permission issues
      - ./db/mysql-init-scripts:/docker-entrypoint-initdb.d
    env_file: .env.db
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password  # Optional (for root access)
    expose:
      - 3306  
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: 
  web-code:

secrets:
  db-password:
    file: ./db/password.txt 
  db-root-password:
    file: ./db/root_password.txt