# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    restart: always
    ports: 
      - 8080:80
    env_file: .env
    environment:
      - APP_ENV=production
      - USER_NAME="NinjaEvents"
      - MAIL_RECIPIENT="trashkan18@gmail.com"
      - MAIL_SENDER="ninjaevents@zohomail.eu"
      - MAIL_APP_PASSWORD="Q226neH1b3NJ"
      - BASE_URL="http://localhost:8080"
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - MYSQL_DATABASE=projetevenements
      - MYSQL_USER=nina
      - MYSQL_PASSWORD=wachter18

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html:Z
      - ./logs:/var/log/apache2  # Optional: Apache logs


  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: db
    image: mysql:8.0
    restart: always
    #user: "1000:1000"   //testerror
    #secrets:
     # - db-password
     # - db-root-password
    volumes:
      - ./db/db-data:/var/lib/mysql # MySQL stores data here, testerror : add :Z to fix permission issues
      - ./db/mysql-init-scripts:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      #- MYSQL_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=M0tDeP4sse
      - MYSQL_DATABASE=projetevenements
      - MYSQL_USER=nina
      - MYSQL_PASSWORD=wachter18      
      - MYSQL_PORT=3306
     # - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password  
    ports:
      - "3307:3306"  
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: 

#secrets:
  #db-root-password:
    #file: ./db/root_password.txt